services:
  frontend:
    tty: true
    build:
      context: frontend
      target: dependencies
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app:rw
    command: npm run dev

  backend:
    tty: true
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app:rw
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - dev.env
    depends_on:
      mysql:
        condition: service_healthy
      valkey:
        condition: service_healthy
      twilight:
        condition: service_started

  bot:
    tty: true
    build: backend
    volumes:
      - ./backend:/app:ro
    command: python manage.py runbot
    restart: unless-stopped
    env_file:
      - dev.env
    depends_on:
      mysql:
        condition: service_healthy
      valkey:
        condition: service_healthy
      twilight:
        condition: service_started

  rq:
    tty: true
    build: backend
    volumes:
      - ./backend:/app:ro
    command: python manage.py rqworker high default
    env_file:
      - dev.env
    depends_on:
      mysql:
        condition: service_healthy
      valkey:
        condition: service_healthy

  mysql:
    image: mysql:9.0
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - dev.env
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 10

  valkey:
    image: valkey/valkey:8
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 1s
      timeout: 5s
      retries: 10

  twilight:
    image: ghcr.io/twilight-rs/http-proxy
    env_file:
      - dev.env

volumes:
  mysql-data:
