[project]
name = "datarod"
version = "1.0.0"
description = "Phoenix Archive (datarod)"
authors = ["Winston Astrachan"]
readme = "../README.md"
requires-python = "==3.13.*"

dependencies = [
    "django<6.0.0",
    "gunicorn",
    "discord-py",
    "mysqlclient",
    "django-rq",
    "requests",
    "graphene-django==3.2.2",
    "django-filter",
    "social-auth-app-django",
    "django-cors-headers",
    "beautifulsoup4",
    "pillow",
    "whitenoise",
    "graphene-file-upload",
]

[dependency-groups]
dev = [
    "ruff",
    "ty",
]

[tool.uv]
exclude-newer = "7 days"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py313"
exclude = [
    ".venv/",
]

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "I", # isort
]
ignore = [
    "F403", # unable to detect undefined names (import *)
    "E501", # line too long
    "E741", # ambiguous variable name
    "E731", # do not assign a lambda expression, use a def
]
fixable = [
    "I", # isort
    "E722", # don't use bare except
    "F401", # unused imports
    "F841", # variable assigned but not used
    "E711", # comparison with None should be 'is None'
    "F541", # f-string without any placeholders
    "E712", # avoid equality comparisons with True
]

[tool.ruff.lint.isort]
order-by-type = true
combine-as-imports = true
from-first = false
default-section = "third-party"
section-order = [
    "future",
    "standard-library",
    "third-party",
    "django",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"django" = ["django"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
