"""
Django settings for datarod project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datarod.settings import *
from pathlib import Path

from corsheaders.defaults import default_headers

from utils.environment import get_env


SECRET_KEY = "1sts@=(-3e#xlab$pnn0x+gmo7=_0m97&r%7_4dj(yc9!$^%qs"

DEBUG = False

ALLOWED_HOSTS = ["api.ussphoenixarchive.com"]
CSRF_TRUSTED_ORIGINS = [
    "https://api.ussphoenixarchive.com",
    "https://ussphoenixarchive.com",
]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/(.+)?\.?ussphoenixarchive\.com$",
]
CORS_ALLOW_HEADERS = (
    *default_headers,
    "accept-language",
)

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# SECURITY WARNING: this password is only for development use!

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "datarod",
        "USER": "backend",
        "PASSWORD": "0f203eb839e64cff091eec9d9cee0162",
        "HOST": "mysql",
        "PORT": "3306",
    }
}

SOCIAL_AUTH_LOGIN_REDIRECT_URL = "https://ussphoenixarchive.com/"
SOCIAL_AUTH_LOGIN_ERROR_URL = "https://ussphoenixarchive.com/error"
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
