# Generated by Django 5.0.7 on 2024-07-20 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="author id"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscordChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="channel id"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("topic", models.TextField(blank=True, null=True)),
                ("archive_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("quarters", "Crew Quarters"),
                            ("other", "Other"),
                        ],
                        default="event",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscordMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="message id"
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw_message", models.JSONField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="archive.discordauthor",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.discordchannel",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="name in use from"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="name in use to"
                    ),
                ),
                (
                    "profile_picture",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "discord_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="archive.discordauthor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "identities",
            },
        ),
        migrations.AddField(
            model_name="discordchannel",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archive.tag",
            ),
        ),
    ]
