# Generated by Django 5.0.7 on 2024-07-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_remove_author_name_remove_nickname_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nickname",
            name="name",
            field=models.CharField(max_length=96, verbose_name="nickname"),
        ),
    ]
