# Generated by Django 5.0.7 on 2024-07-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_alter_nickname_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(
                choices=[
                    ("events", "Events"),
                    ("quarters", "Crew Quarters"),
                    ("phoenixb", "Phoenix B"),
                    ("shore", "Shore Leaves"),
                    ("starfleet", "Starfleet Command"),
                    ("other", "Other"),
                ],
                default="events",
                max_length=64,
            ),
        ),
    ]
