# Generated by Django 5.1.2 on 2024-11-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0005_nickname_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners"),
        ),
    ]
